name: flutter_ocr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.3
  excel: ^3.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/sample.xlsx
    - assets/languages.xlsx
